### ISSUE TITLE
Add more hints to the Hacktoberfest/Python/Guess_Game.py

### ISSUE THREAD

**Issue by 1-Rishabh-Jain-1** [Gawsan/Hacktoberfest#18]
I wanna change the code to include more hints for the user like 'multiple of' and 'even or odd'

**Comment by Gawsan** [comment]
carry on

**Comment by 1-Rishabh-Jain-1** [comment]
I have updated the file to resolve this issue

**Comment by 1-Rishabh-Jain-1** [comment]
please accept the pull request also
